export const itens = [
  {
    id: 1,
    categoria: 'VINHOS',
    ordem: 5,
    nome: 'Trapiche Vineyard',
    subtitulo: 'Vinho tinto argentino',
    descricao:'Merlot Cabernet sauvignon chardonnay',
    preco: 90,
    combo: 0,
    foto: '',
    ativo: true
},
{
    id: 2,
    categoria: 'VINHOS',
    ordem: 5,
    nome: 'Reservado',
    subtitulo: 'Vinho tinto chileno',
    descricao:'Carmenere Cabernet sauvignon malbec argentino sweet red chileno rose',
    preco: 70,
    combo: 0,
    foto: '',
    ativo: true
},
{
    id: 3,
    categoria: 'VINHOS',
    ordem: 5,
    nome: 'Redenz-vous',
    subtitulo: 'Vinho tinto Francês',
    descricao:'Pinot Noir Merlot - Cabernet',
    preco: 210,
    combo: 0,
    foto: '',
    ativo: true
},
{
    id: 4,
    categoria: 'VINHOS',
    ordem: 5,
    nome: 'Julia florista',
    subtitulo: 'Vinhos Portugueses',
    descricao:'Cor rubi. aroma frutado com frutos vermelhos maduros. sabor agradável, macio e redondo com final agradável.',
    preco:90,
    combo: 0,
    foto: '',
    ativo: true
},
{
    id: 5,
    categoria: 'VINHOS',
    ordem: 5,
    nome: 'Cartuxa EA',
    subtitulo: 'Vinhos Portugueses',
    descricao:'Aroma frutado, com notas vegetais, vinho fresco com uma ligeira adstringência, um vinho jovem e pronto para beber.',
    preco:180,
    combo: 0,
    foto: '',
    ativo: true
},
{
    id: 6,
    categoria: 'VINHOS',
    ordem: 5,
    nome: 'Olaria suave',
    subtitulo: 'Vinhos Portugueses',
    descricao:'Leve e doce, com aromas de frutas brancas e um toque de mel',
    preco: 90,
    combo: 0,
    foto: '',
    ativo: true
},
{
    id: 7,
    categoria: 'VINHOS',
    ordem: 5,
    nome: 'Trapiche Vineyard',
    subtitulo: 'Vinho Tinto Argentino',
    descricao:'Merlot Cabernet sauvignon chardonnay',
    preco: 90,
    combo: 0,
    foto: '',
    ativo: true
  },
  {
    id: 7,
    categoria: 'CREPES',
    ordem: 1,
    nome: 'Estrasburg',
    subtitulo: 'Crepe Salgado',
    descricao:'Filet Mignon, cebola caramelizada, queijo tomate cereja e cream cheese.',
    preco: 90,
    combo: 0,
    foto: '',
    ativo: true
  },
]